name = "payone"
account_id = "{ACCOUNT_ID}"
zone_id = "{ZONE_ID}"
route = "{ROUTE}"


[vars]
SCREENSHOT_PROVIDER = "satori"
BASE_URL = ""

[[kv_namespaces]]
binding = ""
id = ""

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]